### ISSUE TITLE
SVG support

### ISSUE THREAD

**Issue by falkTX** [brummer10/XUiDesigner#2]
Hi, is it possible to support SVG in addition to PNG?
More and more people are using high-dpi screens, even on Linux. With PNGs we could use a 1x and 2x scale of the same assets, but then fractional scale factors dont work so well. Shipping with resources for all scale factors does not.. scale well.
So SVG would be nice (or others ways to scale up, doesnt have to specifically be SVG)

**Comment by brummer10** [comment]
So, SVG support is on it's way. I've implemented it via nanosvg https://github.com/memononen/nanosvg in libxputty and it works so far. I do base64 encoding on the SVG to allow embedding the file into the binary. For loading into a cairo surface it will be decoded from the binary. Now I need to implement SVG handling in XUiDesigner so that SVG's could be finally used to create LV2 GUI's.

**Comment by brummer10** [comment]
Proper SVG support is now implemented.
